# Panda series Started

In [1]:
import pandas as pd
import numpy as np

# Codes starts

In [2]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([100,200,400])
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

# Using a different List as Indexing |

In [3]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [4]:
#using array in list
pd.Series(arr,index=labels)

a    100
b    200
c    400
dtype: int64

# Playing with data

In [5]:
data_frame={'name':["John","Anna","Peter","Abrham"]
            ,'age':[30,40,43,31],
            'Salary':[60000,80000,90000,70000]}

df=pd.DataFrame(data_frame)
print(df)

# Making List 
my_list=[['john',30,60000],['Anna',40,80000],['Peter',43,90000],['Abraham',31,70000]]
labels=['a','b','c']
# Adding COloumn while dealing with list
df2=pd.DataFrame(my_list,columns=labels)
df2

     name  age  Salary
0    John   30   60000
1    Anna   40   80000
2   Peter   43   90000
3  Abrham   31   70000

         a   b      c
0     john  30  60000
1     Anna  40  80000
2    Peter  43  90000
3  Abraham  31  70000

# Slecting Column

In [6]:

data_frame={"name":["John","Anna","Peter","Abrham"]
            ,"age":[30,40,43,31],
            "Salary":[60000,80000,90000,70000]}

df=pd.DataFrame(data_frame)
#df.lor[['name','age']]
df2.loc[[0,1]]

      a   b      c
0  john  30  60000
1  Anna  40  80000

# Selecting Subset of ROws And Column

In [7]:
df.loc[[0,1],["age","Salary"]]

   age  Salary
0   30   60000
1   40   80000

In [8]:
df.loc[[2,3],["name","age"]]

     name  age
2   Peter   43
3  Abrham   31

# Conditional Statement

In [10]:
df[df["age"]>32]

    name  age  Salary
1   Anna   40   80000
2  Peter   43   90000

In [16]:
# USing & and | 

df[(df["age"]>32) & (df["Salary"]>=80000)]
print("Using OR Function")
df[(df["age"]>43) | (df["Salary"]>60000)]

Using OR Function

     name  age  Salary
1    Anna   40   80000
2   Peter   43   90000
3  Abrham   31   70000

# Missing Data

In [18]:
data_frame={
    'a':[1,2,np.nan,4,5],
    'b':[np.nan,2,3,4,5],
    'c':[1,2,3,np.nan,np.nan],
    'd':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data_frame)
df

     a    b    c    d
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

Finfing Missing Element

In [22]:
df.isna()

       a      b      c      d
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

FINDING total no of missing element

In [23]:
df.isna().sum()

a    1
b    1
c    2
d    3
dtype: int64

Removing Null value rows

In [25]:
df.dropna()
#Since all the rows contains atleast one null values so all rows are deleted

Empty DataFrame
Columns: [a, b, c, d]
Index: []

In [26]:
# Using Thresh value as COndition

df.dropna(thresh=3)
# it will return rows that contains atleast 3 known values in it

     a    b    c    d
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

FILLING THE MISSING DATA

In [27]:
df.fillna(3)
#it will replace all the Nan values to 3

     a    b    c    d
0  1.0  3.0  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  3.0  3.0
4  5.0  5.0  3.0  5.0

In [29]:
# Substituing Using a list 
values={'a':20,'b':30,'c':40,'d':50}
df.fillna(value=values)

      a     b     c     d
0   1.0  30.0   1.0   1.0
1   2.0   2.0   2.0  50.0
2  20.0   3.0   3.0  50.0
3   4.0   4.0  40.0  50.0
4   5.0   5.0  40.0   5.0

In [31]:
# Replacing All Values With their Mean
df.fillna(df.mean())

     a    b    c    d
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0