# Phase 2 of Pandas Liberary Learning Starts

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Data Frame About Employess
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [4]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [5]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [6]:
#inner is used to connect the data of 1st frame to second frame
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [7]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

# Using COncatination

In [8]:
pd.concat((employees,salaries))

   employee_id   name department   salary    bonus
0            1   John         HR      NaN      NaN
1            2   Anna         IT      NaN      NaN
2            3  Peter    Finance      NaN      NaN
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
0            1    NaN        NaN  60000.0   5000.0
1            2    NaN        NaN  80000.0  10000.0
2            3    NaN        NaN  65000.0   7000.0
3            6    NaN        NaN  70000.0   8000.0
4            7    NaN        NaN  90000.0  12000.0

In [11]:
# Concatination Using Axis
pd.concat((employees,salaries),axis=1)
print("\n")
pd.concat((employees,salaries),axis=0)

   employee_id   name department   salary    bonus
0            1   John         HR      NaN      NaN
1            2   Anna         IT      NaN      NaN
2            3  Peter    Finance      NaN      NaN
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
0            1    NaN        NaN  60000.0   5000.0
1            2    NaN        NaN  80000.0  10000.0
2            3    NaN        NaN  65000.0   7000.0
3            6    NaN        NaN  70000.0   8000.0
4            7    NaN        NaN  90000.0  12000.0

# Joining Two DataFrames Together

In [12]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [13]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [14]:
# UsinG how
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [15]:
# UsinG how
df1.join(df2,how='inner')

      name  score
2      Bob     85
3  Charlie     90

# Group By Aggregration

In [17]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data) 
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [22]:
# Using Group Functions
df.groupby(['Category'])['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [23]:
# Using Group Functions
df.groupby(['Store'])['Quantity'].sum()

Store
S1    58
S2    65
Name: Quantity, dtype: int64

 Using Aggregation ,(Aggregation is used to find ['Mean','Median',Max','min','count','std','sum'])

In [26]:
df['Sales'].agg(['sum','mean','median','max','min','std','count'])

sum       1500.000000
mean       187.500000
median     190.000000
max        300.000000
min        100.000000
std         66.062741
count        8.000000
Name: Sales, dtype: float64

# Pivot Tabels

In [27]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    451     90   John  January      Q1
1  2023-01-02       B   West    139     41   Mary  January      Q1
2  2023-01-03       C  North    294     56    Bob  January      Q1
3  2023-01-04       D  South    235     15  Alice  January      Q1
4  2023-01-05       A   East    774     25   John  January      Q1
5  2023-01-06       B   West    845     29   Mary  January      Q1
6  2023-01-07       C  North    344     30    Bob  January      Q1
7  2023-01-08       D  South    570     75  Alice  January      Q1
8  2023-01-09       A   East    336     57   John  January      Q1
9  2023-01-10       B   West    502     25   Mary  January      Q1
10 2023-01-11       C  North    553     95    Bob  January      Q1
11 2023-01-12       D  South    272     30  Alice  January      Q1
12 2023-01-13       A   East    688     82   John  January      Q1
13 2023-01-14       B   West    290     31   Mary  January      Q1
14 2023-01-15       C  North    461     75    Bob  January      Q1
15 2023-01-16       D  South    209     49  Alice  January      Q1
16 2023-01-17       A   East    776     65   John  January      Q1
17 2023-01-18       B   West    659     65   Mary  January      Q1
18 2023-01-19       C  North    784     98    Bob  January      Q1
19 2023-01-20       D  South    652     69  Alice  January      Q1

In [33]:
obj=df.groupby(['Product','Region'])

for i,v in obj :
    print(i)
    print("\n")
    print(v)

('A', 'East')


         Date Product Region  Sales  Units   Rep    Month Quarter
0  2023-01-01       A   East    451     90  John  January      Q1
4  2023-01-05       A   East    774     25  John  January      Q1
8  2023-01-09       A   East    336     57  John  January      Q1
12 2023-01-13       A   East    688     82  John  January      Q1
16 2023-01-17       A   East    776     65  John  January      Q1
('B', 'West')


         Date Product Region  Sales  Units   Rep    Month Quarter
1  2023-01-02       B   West    139     41  Mary  January      Q1
5  2023-01-06       B   West    845     29  Mary  January      Q1
9  2023-01-10       B   West    502     25  Mary  January      Q1
13 2023-01-14       B   West    290     31  Mary  January      Q1
17 2023-01-18       B   West    659     65  Mary  January      Q1
('C', 'North')


         Date Product Region  Sales  Units  Rep    Month Quarter
2  2023-01-03       C  North    294     56  Bob  January      Q1
6  2023-01-07       C  North    344     30  Bob  January      Q1
10 2023-01-11       C  North    553     95  Bob  January      Q1
14 2023-01-15       C  North    461     75  Bob  January      Q1
18 2023-01-19       C  North    784     98  Bob  January      Q1
('D', 'South')


         Date Product Region  Sales  Units    Rep    Month Quarter
3  2023-01-04       D  South    235     15  Alice  January      Q1
7  2023-01-08       D  South    570     75  Alice  January      Q1
11 2023-01-12       D  South    272     30  Alice  January      Q1
15 2023-01-16       D  South    209     49  Alice  January      Q1
19 2023-01-20       D  South    652     69  Alice  January      Q1

In [34]:
# Using Pivot_Table for converting and simplifiying the data

In [36]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product")
# it gives the mean values and gives NaN where it cannot find any data

Product      A      B      C      D
Region
East     605.0    NaN    NaN    NaN
North      NaN    NaN  487.2    NaN
South      NaN    NaN    NaN  387.6
West       NaN  487.0    NaN    NaN

In [ ]:
# CHanging the mean value to overall sum and count , max , median
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc=["sum","count","max","median"])

            sum                         count                   max         \
Product       A       B       C       D     A    B    C    D      A      B
Region
East     3025.0     NaN     NaN     NaN   5.0  NaN  NaN  NaN  776.0    NaN
North       NaN     NaN  2436.0     NaN   NaN  NaN  5.0  NaN    NaN    NaN
South       NaN     NaN     NaN  1938.0   NaN  NaN  NaN  5.0    NaN    NaN
West        NaN  2435.0     NaN     NaN   NaN  5.0  NaN  NaN    NaN  845.0

                      median
Product      C      D      A      B      C      D
Region
East       NaN    NaN  688.0    NaN    NaN    NaN
North    784.0    NaN    NaN    NaN  461.0    NaN
South      NaN  652.0    NaN    NaN    NaN  272.0
West       NaN    NaN    NaN  502.0    NaN    NaN

CrossTabs
There is one more function which is used just as count

In [42]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# Operations

In [43]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [44]:
df1.agg("mean")

A      3.0
B     30.0
C    300.0
dtype: float64