In [2]:
import pandas as pd
import numpy as np

https://github.com/AkarshVyas/Pandas-Youtube/blob/main/anime.csv


#make a new column for episode count
#make a new column for time stamp
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count
#which is the longest running anime

In [3]:
data=pd.read_csv("anime.csv")
print(data)

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [4]:
data.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [5]:
data.loc[4]["Title"]

'Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview'

# Q 1 : Make a new column for episode count

In [6]:
def episode_count(txt) :
    newdata =""
    check=False
    for i in txt :
        if i==")" :
            check=False
            break
        if check==True :
            newdata=newdata+i
        if i=="(" :
            check=True
    return newdata   
       
    
data["Episode Count"] = data["Title"].apply(episode_count)

In [7]:
data.head()

,Rank,Title,Score,Episode Count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64 eps
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24 eps
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13 eps
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51 eps
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10 eps

In [ ]:
def episode_number (txt) :
    check=False
    newdata= ""
    for i in txt :
        if i=="e":
            check=True;
        if check == True :
           break
        if check== False :
            newdata=newdata+i
    return newdata

Removing Eps from Episode COunt

In [9]:
data["Episode Count"]=data["Episode Count"].apply(episode_number)
data.head()

,Rank,Title,Score,Episode Count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10

In [10]:
data["Episode Count"].dtype

In [11]:
# COnverting the STring Type of Episode COunt to integer
data["Episode Count"]=data["Episode Count"].astype(int)

In [12]:
data["Episode Count"].dtype

dtype('int64')

 # Q : 2 Make a new column for time stamp

In [26]:
data.loc[5]["Title"]

"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members"

In [25]:
def start_time(txt) :
    check=False
    newdata=""
    for i in txt :
        if check==True :
            if i=="-" or i== "--" :
                check=False
                break   
            newdata=newdata+i
        if i==")":
            check=True
            continue
        
        
    return newdata

data["Start Time"]=data["Title"].apply(start_time)
data.head()

,Rank,Title,Score,Episode Count,Start Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019

 Writing the End Time

In [33]:
data.loc[3]["Title"]

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [32]:
def end_time(txt) :
    check=False
    newdata=""
    for i in range (len(txt)) :
        if txt[i]=="-" :
            for j in range (10) :
                newdata=newdata+txt[j+i+1]
        
    return newdata

data["End Time"]=data["Title"].apply(end_time)
data.head()

,Rank,Title,Score,Episode Count,Start Time,End Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009,Jul 20103
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011,Sep 20112
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022,henTV (13 Dec 20224
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015,Mar 20166
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019,Jul 20192

As you can see that when we try to use this method some of the title might have another - , so we are not able to get our desired product
But there is one more observation that all the date start Time +End Time start just after episode number or  after ")", so we will count that

In [36]:
data.loc[3]["Title"]

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [42]:
def time_count (txt) :
    newdata =""
    for i in range (len (txt)) :
        if txt[i]==")" :
            for j in range (1,20):
                newdata=newdata+txt[j+i]
    
    return newdata

data["Time"]=data["Title"].apply(time_count)
data.head()

,Rank,Title,Score,Episode Count,Start Time,End Time,Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009,Jul 20103,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011,Sep 20112,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022,henTV (13 Dec 20224,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015,Mar 20166,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019,Jul 20192,Apr 2019 - Jul 2019

 So we got the Whole time length of our Anime Series , so now deleting the Columns We Created As " Start Time and End Time "

In [51]:
# Deleting the Column of Start Time 
data.drop("Start Time",axis=1,inplace=True)
data.head()

,Rank,Title,Score,Episode Count,End Time,Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Jul 20103,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Sep 20112,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,henTV (13 Dec 20224,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Mar 20166,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Jul 20192,Apr 2019 - Jul 2019

In [57]:
# Deleting the Column of End Time
data.drop("End Time",axis=1,inplace=True)
data.head()

,Rank,Title,Score,Episode Count,Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

# Q 3: #which anime has the highest score

In [78]:
# Since we have a separate table for the Score we will just use the abbervation function 
max_score=data["Score"].agg(max)
id=data["Score"].idxmax()
print("The Max Score is " ,max_score ,"\n The Name of Anime Which has Highest Score is : \n",data.loc[id,"Title"])

The Max Score is  9.1
 The Name of Anime Which has Highest Score is :
 Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview

# Q 4 : Give me top 5 highest scoring anime

In [81]:
data.sort_values("Score",ascending=False).head(5)

,Rank,Title,Score,Episode Count,Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

# Q 5 :which anime has the highest episode count

In [88]:
id=data["Episode Count"].idxmax()
print("The Maximum no of Episode is :",data.loc[id,"Episode Count"]," \nThe Anime With Maximum no of episode count is : ",data.loc[id,"Title"])

The Maximum no of Episode is : 201
The Anime With Maximum no of episode count is :  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members

 # Q 6 : animes with top 5 episode count

In [91]:
data.sort_values("Episode Count",ascending=False).head(5)

,Rank,Title,Score,Episode Count,Time
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005

# Q 7 :which is the longest running anime

In [96]:
# Spliting the Start Date and The End date
data[["Start","End"]]=data["Time"].str.split("-",expand=True)
data.head()

,Rank,Title,Score,Episode Count,Time,Start,End
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,Apr 2009,Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,Apr 2011,Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,Oct 2022,Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,Apr 2015,Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,Apr 2019,Jul 2019

In [103]:
data["Start"]=pd.to_datetime(data["Start"],format="%b %Y")
data.head()

,Rank,Title,Score,Episode Count,Time,Start,End
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,2009-04-01,Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,2011-04-01,Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2022-10-01,Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,2015-04-01,Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,2019-04-01,Jul 2019

In [107]:
data["End"]=pd.to_datetime(data["End"],format="%b %Y")
data.head()

,Rank,Title,Score,Episode Count,Time,Start,End
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,2009-04-01,2010-07-01
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,2011-04-01,2011-09-01
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2022-10-01,2022-12-01
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,2015-04-01,2016-03-01
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,2019-04-01,2019-07-01

In [108]:
data["Duration"]=data["End"]-data["Start"]
data.head()

,Rank,Title,Score,Episode Count,Time,Start,End,Duration
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,2009-04-01,2010-07-01,456 days
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,2011-04-01,2011-09-01,153 days
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,61 days
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,2015-04-01,2016-03-01,335 days
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,2019-04-01,2019-07-01,91 days

In [114]:
id=data["Duration"].idxmax()
print(id)
print("The Longest Runnuing Anime is :" , data.loc[id,"Title"],"\n This show has runned over :",data.loc[id,"Duration"])

11
The Longest Runnuing Anime is : Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members
 This show has runned over : 3347 days 00:00:00

In [116]:
data.loc[11]

Rank                                                            12
Title            Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
Score                                                         9.02
Episode Count                                                  110
Time                                           Jan 1988 - Mar 1997
Start                                          1988-01-01 00:00:00
End                                            1997-03-01 00:00:00
Duration                                        3347 days 00:00:00
Name: 11, dtype: object

#                                        This Project Work is Done